[build]
  base    = "frontend"      # Tells Netlify to look inside the frontend directory
  publish = "dist"         # Specifies the directory to publish
  command = "npm install && npm run build"  # Build command 

  [functions]
  directory = "backend/functions"
